spring:
  application:
    name: gateway

server:
  port: 8080
  servlet:
    context-path: /gateway

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    hostname: localhost
zuul:
  sensitive-headers: Cookie

logging:
  level:
    web: DEBUG